// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Grafs")>]
[<assembly: AssemblyProductAttribute("Grafs")>]
[<assembly: AssemblyDescriptionAttribute("A F# implementation of GraphQL language for server and client")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Grafs.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Grafs"
    let [<Literal>] AssemblyProduct = "Grafs"
    let [<Literal>] AssemblyDescription = "A F# implementation of GraphQL language for server and client"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
